// src/pages/main/guides_service/index.tsx
import {
    Box,
    Card,
    SelectChangeEvent,
    Table,
    TableBody,
    TableCell,
    TableContainer,
    TableHead,
    TablePagination,
    TableRow,
    Toolbar,
    Typography,
} from '@mui/material';
import { LoadingLinear } from '@atoms/loadings/linear';
import { DropDownStatusCode } from '@organisms/dropdowns/status_code';

import { DatePickerRange } from '@organisms/date_picker_range';
import { DropDownTypeServices } from '@organisms/dropdowns/type_services';
import { DropDownNovelties } from '@organisms/dropdowns/novelties';
import { useCallServices } from '@hooks/use_call_services';
import { guideServices } from '@services/guides_service';
import { useProfile } from '@storages/zustand/profile';
import { guidesServiceAdapters } from '@models/guides_service/adapters';

import styles from './styles.module.css';
import { ChangeEvent, MouseEvent, useEffect, useState } from 'react';
import {
    TGuideServiceDOM,
    TGuideServiceFilterDOM,
} from '@models/guides_service/entities';
import { addCommodityUnits } from '@helpers/add_commodity_units';
import { formatDateView } from '@helpers/format_date_view';
import { getFirstDateInMonth, getLastDateInMonth, getMillisDate } from '@tools/datetime';
import { DateRange } from '@mui/lab';
import { DateTime } from 'luxon';
import { ButtonFloatingAdd } from '@molecules/buttons/floating_add';
import { useNavigate } from 'react-router-dom';
import { ROUTES } from '@constants/routes';

export default function MainGuidesService() {
    const { profile } = useProfile();

    const [guides, setGuides] = useState<TGuideServiceDOM[]>([]);
    const [filters, setFilters] = useState<TGuideServiceFilterDOM>({
        userId: profile.id,
        status: true,
        clientOrigin: true,
        clientDestination: true,
        pointSaleOrigin: true,
        pointSaleDestination: true,
        service: true,
        limit: 0,
        offset: 0,
        startDate: undefined,
        endDate: undefined,
        statusId: '',
        noveltyId: '',
        serviceId: '',
    });
    const [total, setTotal] = useState(1);
    const [offset, setOffset] = useState(0);
    const [limit, setLimit] = useState(10);

    const [dateFilter, setDateFilter] = useState<DateRange<DateTime>>([
        getFirstDateInMonth(),
        getLastDateInMonth(),
    ]);

    const navigate = useNavigate();

    const { loading, callEndpointList } = useCallServices();

    useEffect(() => {
        getGuides();
    }, [filters, dateFilter]);

    const getGuides = async () => {
        try {
            const { items, total: totals } = await callEndpointList(
                guideServices.getAll({
                    ...filters,
                    startDate: getMillisDate(dateFilter[0]!),
                    endDate: getMillisDate(dateFilter[1]!),
                    limit,
                    offset: offset === 0 ? 0 : offset * limit,
                }),
                guidesServiceAdapters,
            );
            setGuides([...items]);
            if (totals !== total) setTotal(totals);
        } catch (e) {
            console.log({ e });
        }
    };

    const handleSelectGuide = (guide: TGuideServiceDOM) => {
        navigate(`${ROUTES.GUIDES_SERVICE}/${guide.id}`);
    };

    const handleChangeStatusFilter = ({ target }: SelectChangeEvent) => {
        setFilters({
            ...filters,
            statusId: target.value,
        });
    };

    const handleChangeTypeServiceFilter = ({ target }: SelectChangeEvent) => {
        setFilters({
            ...filters,
            serviceId: target.value,
        });
    };

    const handleChangeNoveltyFilter = ({ target }: SelectChangeEvent) => {
        setFilters({
            ...filters,
            noveltyId: target.value,
        });
    };

    const handleChangeDateFilter = (date: DateRange<DateTime<boolean>>) => {
        setDateFilter(date);
    };

    const handleChangeLimit = ({ target }: ChangeEvent<HTMLInputElement>) => {
        setLimit(+target.value);
    };

    const handleChangeOffset = (
        _: MouseEvent<HTMLButtonElement> | null,
        page: number,
    ) => {
        setOffset(page);
    };

    const handleCreateGuide = () => navigate(ROUTES.GUIDES_SERVICE_CREATE);

    return (
        <>
            <ButtonFloatingAdd onClick={handleCreateGuide} />
            <Box className={styles.container}>
                <Card className={styles.box_content}>
                    <Toolbar>
                        <form /* onSubmit={handleSubmit} */ className={styles.form}>
                            <DatePickerRange
                                value={dateFilter}
                                onChange={handleChangeDateFilter}
                            />
                            <DropDownTypeServices
                                onChange={handleChangeTypeServiceFilter}
                                value={filters.serviceId}
                                showvoid
                            />
                            <DropDownNovelties
                                onChange={handleChangeNoveltyFilter}
                                value={filters.noveltyId}
                                showvoid
                            />
                            <DropDownStatusCode
                                onChange={handleChangeStatusFilter}
                                value={filters.statusId}
                                className={styles.input}
                                type="guides_service"
                                showvoid
                            />
                            <input type="submit" hidden />
                        </form>
                    </Toolbar>
                    <TableContainer className={styles.table_container}>
                        <Table stickyHeader>
                            <TableHead>
                                <TableRow>
                                    <TableCell className={styles.head_txt}>
                                        Fecha Y Hora
                                    </TableCell>
                                    <TableCell className={styles.head_txt}>
                                        Guía
                                    </TableCell>
                                    <TableCell className={styles.head_txt}>
                                        Estado
                                    </TableCell>
                                    <TableCell className={styles.head_txt}>
                                        Remitente
                                    </TableCell>
                                    <TableCell className={styles.head_txt}>
                                        Dir Remitente
                                    </TableCell>
                                    <TableCell className={styles.head_txt}>
                                        Tel Remitente
                                    </TableCell>
                                    <TableCell className={styles.head_txt}>
                                        Origen
                                    </TableCell>
                                    <TableCell className={styles.head_txt}>
                                        Destinatario
                                    </TableCell>
                                    <TableCell className={styles.head_txt}>
                                        Dir Destino
                                    </TableCell>
                                    <TableCell className={styles.head_txt}>
                                        Tel Destino
                                    </TableCell>
                                    <TableCell className={styles.head_txt}>
                                        Destino
                                    </TableCell>
                                    <TableCell className={styles.head_txt}>
                                        Servicio
                                    </TableCell>
                                    <TableCell className={styles.head_txt}>
                                        Unidades
                                    </TableCell>
                                    <TableCell className={styles.head_txt}>
                                        Total $
                                    </TableCell>
                                </TableRow>
                            </TableHead>
                            {loading && (
                                <TableBody>
                                    <TableRow>
                                        <TableCell
                                            sx={{
                                                padding: 0,
                                            }}
                                            colSpan={14}
                                        >
                                            <LoadingLinear />
                                        </TableCell>
                                    </TableRow>
                                </TableBody>
                            )}
                            <TableBody>
                                {guides.map((guide, i) => (
                                    <TableRow
                                        onClick={() => handleSelectGuide(guide)}
                                        className={styles.column_body}
                                        hover
                                        key={i}
                                    >
                                        <GuideRow guide={guide} />
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                        {guides.length === 0 && !loading && (
                            <Typography className={styles.not_found_txt}>
                                Sin Resultados
                            </Typography>
                        )}
                    </TableContainer>

                    <TablePagination
                        count={total}
                        page={offset}
                        rowsPerPage={limit}
                        rowsPerPageOptions={[10, 50, 100]}
                        onPageChange={handleChangeOffset}
                        onRowsPerPageChange={handleChangeLimit}
                        component={'div'}
                        labelRowsPerPage="Guias por pagina"
                    />
                </Card>
            </Box>
        </>
    );
}

type TGuideRowProps = {
    guide: TGuideServiceDOM;
};

const GuideRow = ({ guide }: TGuideRowProps) => {
    return (
        <>
            <TableCell>{formatDateView(guide.createdAt)}</TableCell>
            <TableCell>{guide.number}</TableCell>
            <TableCell>{guide.status?.name}</TableCell>
            {guide.clientOrigin?.natural ? (
                <TableCell>
                    {guide.clientOrigin?.firstName} {guide.clientOrigin?.lastName}
                </TableCell>
            ) : (
                <TableCell>
                    {guide.clientOrigin?.businessName} {guide.clientOrigin?.nit}
                </TableCell>
            )}

            <TableCell>{guide.clientOrigin?.address}</TableCell>
            <TableCell>{guide.clientOrigin?.numberMovil}</TableCell>
            <TableCell>{guide.pointSaleOrigin?.municipality}</TableCell>

            {guide.clientDestination?.natural ? (
                <TableCell>
                    {guide.clientDestination?.firstName}
                    {guide.clientDestination?.lastName}
                </TableCell>
            ) : (
                <TableCell>
                    {guide.clientDestination?.businessName}
                    {guide.clientDestination?.nit}
                </TableCell>
            )}

            <TableCell>{guide.clientDestination?.address}</TableCell>
            <TableCell>{guide.clientDestination?.numberMovil}</TableCell>
            <TableCell>{guide.pointSaleDestination?.municipality}</TableCell>
            <TableCell>{guide.service?.name}</TableCell>
            <TableCell>{addCommodityUnits(guide.commodity)}</TableCell>
            <TableCell>${guide.price}</TableCell>
        </>
    );
};

// src/routes/guides_service/+page.svelte
<script lang="ts">
	import Card from '@smui/card';
	import DataTable, { Body, Cell, Head, Label, Pagination, Row } from '@smui/data-table';
	import IconButton from '@smui/icon-button';
	import LinearLoading from '$atoms/linear_loading.svelte';
	import { callServices } from '$directives/call_services';
	import { onDestroy, onMount } from 'svelte';
	import P from '$atoms/p.svelte';
	import { statusCodeAdapters } from '$models/status_code/adapters';
	import TextfieldWithIcon from '$atoms/textfield_wih_icon.svelte';
	import type { TSelectOption } from '$molecules/types/select';
	import SelectNoHelpertext from '$molecules/select_no_helpertext.svelte';
	import { getAllStatusCode } from '$services/status_code';
	import ButtonFab from '$atoms/button_fab.svelte';
	import SeparatorNotLine from '$atoms/separator_not_line.svelte';
	import { addCommodityUnits, formatDateView } from '$helpers/index';
	import type { TUserFilterDOM } from '$models/users/entities';
	import { goto } from '$app/navigation';
	import {
		getAllGuidesService,
		getGuidesServiceNolveties,
		getGuidesServiceTypeServices
	} from '$services/guides_service';
	import { guidesServiceAdapters } from '$models/guides_service/adapters';
	import type { TGuideServiceDOM } from '$models/guides_service/entities';
	import { profileStore } from '$stores/profile';
	import Textfield from '$atoms/textfield.svelte';
	import Select from '$molecules/select.svelte';

	const { callEndpointList, loading, callEndpointApi, cancelEndpoint } = callServices();
	const {
		callEndpointList: callEndpointListStatus,
		loading: loadingStatus,
		cancelEndpoint: cancelEndpointStatus
	} = callServices();
	const {
		callEndpointList: callEndpointListUserRoles,
		loading: loadingUserRoles,
		cancelEndpoint: cancelEndpointUserRoles
	} = callServices();

	onDestroy(() => {
		cancelEndpoint();
		cancelEndpointStatus();
		cancelEndpointUserRoles();
	});

	onMount(() => {
		getNoveltiesAndServicesType();
		getStatusCode();
	});

	const pagesOptions: TSelectOption[] = [
		{
			label: '10',
			value: 10
		},
		{
			label: '50',
			value: 50
		},
		{
			label: '100',
			value: 100
		}
	];
	let filters: TUserFilterDOM = {
		firstName: '',
		lastName: '',
		documentId: '',
		email: '',
		limit: 10,
		offset: 0,
		status: true
	};
	let filterStatus: string = '';
	let filterNovelty: string = '';
	let filterServicesType: string = '';
	let guides: TGuideServiceDOM[] = [];
	let statusCode: TSelectOption[] = [];
	let noveltiesFilter: TSelectOption[] = [];
	let servicesTypeFilter: TSelectOption[] = [];
	let startTime = '';
	let endTime = '';

	// Pagination
	let rowsPerPage = 10;
	let page = 0;
	$: start = page * rowsPerPage;
	$: end = Math.min(start + rowsPerPage, guides.length);
	$: lastPage = Math.max(Math.ceil(guides.length / rowsPerPage) - 1, 0);
	$: if (page > lastPage) page = lastPage;

	const getStatusCode = async () => {
		try {
			const status = await callEndpointListStatus(
				getAllStatusCode('guides_service'),
				statusCodeAdapters
			);
			const statusMap = status.map(({ name, id }) => ({ label: name, value: id }));

			statusCode = [
				{
					label: '',
					value: ''
				},
				...statusMap
			];
		} catch (e) {
			console.log({ e });
		}
	};

	const getNoveltiesAndServicesType = async () => {
		try {
			const {
				data: { items: novelties }
			} = await getGuidesServiceNolveties().response;
			const {
				data: { items: servicesType }
			} = await getGuidesServiceTypeServices().response;

			const moveltiesMap = novelties.map(({ name, _id }) => ({
				label: name,
				value: _id
			}));

			const servicesTypeMap = servicesType.map(({ name, _id }) => ({
				label: name,
				value: _id
			}));

			noveltiesFilter = [
				{
					label: '',
					value: ''
				},
				...moveltiesMap
			];
			servicesTypeFilter = [
				{
					label: '',
					value: ''
				},
				...servicesTypeMap
			];
		} catch (e) {
			console.log({ e });
		}
	};

	const handleSearchGuide = async (
		startTime: string,
		endTime: string,
		statusId?: string,
		noveltyId?: string,
		serviceId?: string
	) => {
		try {
			const startDate = startTime ? new Date(startTime) : new Date();
			if (!startTime) startDate.setDate(1);
			const endDate = endTime
				? new Date(endTime)
				: new Date(startDate.getFullYear(), startDate.getMonth() + 1, 0);

			guides = await callEndpointList(
				getAllGuidesService({
					...filters,
					userId: $profileStore?.id || '',
					limit: 50,
					offset: 0,
					status: true,
					clientOrigin: true,
					clientDestination: true,
					pointSaleOrigin: true,
					pointSaleDestination: true,
					service: true,
					startDate: startDate.getTime(),
					endDate: endDate.getTime(),
					statusId,
					noveltyId,
					serviceId
				}),
				guidesServiceAdapters
			);
		} catch (e) {
			console.log({ e });
		}
	};

	const handleSelectGuide = (guide: TGuideServiceDOM) => {
		goto(`/guides_service/${guide.id}`);
	};

	const handleCreateUser = () => goto('/guides_service/create');

	const handleAddPage = () => page++;
	const handleSubtractPage = () => page--;
	const handleFirstPage = () => (page = 0);
	const handleLastPage = () => (page = lastPage);

	$: handleSearchGuide(
		startTime,
		endTime,
		filterStatus,
		filterNovelty,
		filterServicesType
	);
</script>

<ButtonFab
	on:click={handleCreateUser}
	style="position: fixed; bottom: 30px; right: 30px;"
	icon="add"
/>
<section>
	<Card padded>
		<form
			on:submit|preventDefault={() =>
				handleSearchGuide(
					startTime,
					endTime,
					filterStatus,
					filterNovelty,
					filterServicesType
				)}
		>
			<div class="box_inputs">
				<Textfield
					type="datetime-local"
					bind:value={startTime}
					label="Fecha de Inicio"
					variant="outlined"
					style="width: 32%;"
				/>
				<Textfield
					type="datetime-local"
					bind:value={endTime}
					label="Fecha Final"
					variant="outlined"
					style="width: 32%;"
				/>
				<Select
					bind:value={filterStatus}
					options={statusCode}
					label="Estado"
					variant="outlined"
					style="width: 32%;"
				/>
			</div>
			<SeparatorNotLine style="margin-top: 10px;" />
			<div class="box_inputs">
				<Select
					bind:value={filterServicesType}
					options={servicesTypeFilter}
					label="Tipo de Servicio"
					variant="outlined"
					style="width: 45%;"
				/>
				<Select
					bind:value={filterNovelty}
					options={noveltiesFilter}
					label="Novedad"
					variant="outlined"
					style="width: 45%;"
				/>
			</div>

			<button type="submit" style="display: none;"></button>
		</form>

		<SeparatorNotLine style="margin: 20px 0;" />

		{#if statusCode.length > 0}
			<Pagination>
				<svelte:fragment slot="rowsPerPage">
					<Label>Filas por Pagina</Label>
					<SelectNoHelpertext
						options={pagesOptions}
						value={rowsPerPage}
						variant="outlined"
					/>

					<span style="margin-left: 40px;">
						{start + 1}-{end} of {guides.length}
					</span>
				</svelte:fragment>

				<IconButton
					class="material-icons"
					on:click={handleFirstPage}
					disabled={page === 0}
				>
					first_page
				</IconButton>
				<IconButton
					class="material-icons"
					on:click={handleSubtractPage}
					disabled={page === 0}
				>
					chevron_left
				</IconButton>
				<IconButton
					class="material-icons"
					on:click={handleAddPage}
					disabled={page === lastPage}
				>
					chevron_right
				</IconButton>
				<IconButton
					class="material-icons"
					on:click={handleLastPage}
					disabled={page === lastPage}
				>
					last_page
				</IconButton>
			</Pagination>
		{/if}
		<DataTable style="height: auto; max-height: 400px; overflow: auto;">
			<LinearLoading
				loading={$loading || $loadingStatus || $loadingUserRoles}
				slot="progress"
				indeterminate
			/>

			<Head>
				<Row>
					<Cell>Fecha y Hora</Cell>
					<Cell>Guía</Cell>
					<Cell>Estado</Cell>
					<Cell>Remitente</Cell>
					<Cell>Dir Remitente</Cell>
					<Cell>Tel Remitente</Cell>
					<Cell>Origen</Cell>
					<Cell>Destinatario</Cell>
					<Cell>Dir Destino</Cell>
					<Cell>Tel Destino</Cell>
					<Cell>Destino</Cell>
					<Cell>Servicio</Cell>
					<Cell>Unidades</Cell>
					<Cell>Total $</Cell>
				</Row>
			</Head>

			<Body>
				{#each guides as item (item.id)}
					<Row style="cursor: pointer;" on:click={() => handleSelectGuide(item)}>
						<Cell>{formatDateView(item.createdAt)}</Cell>
						<Cell>{item.number}</Cell>
						<Cell>{item.status?.name}</Cell>
						{#if item.clientOrigin?.natural}
							<Cell>{item.clientOrigin?.firstName} {item.clientOrigin?.lastName}</Cell>
						{:else}
							<Cell>{item.clientOrigin?.businessName} {item.clientOrigin?.nit}</Cell>
						{/if}
						<Cell>{item.clientOrigin?.address}</Cell>
						<Cell>{item.clientOrigin?.numberMovil}</Cell>
						<Cell>{item.pointSaleOrigin?.municipality}</Cell>

						{#if item.clientDestination?.natural}
							<Cell
								>{item.clientDestination?.firstName}
								{item.clientDestination?.lastName}</Cell
							>
						{:else}
							<Cell
								>{item.clientDestination?.businessName}
								{item.clientDestination?.nit}</Cell
							>
						{/if}
						<Cell>{item.clientDestination?.address}</Cell>
						<Cell>{item.clientDestination?.numberMovil}</Cell>
						<Cell>{item.pointSaleDestination?.municipality}</Cell>
						<Cell>{item.service?.name}</Cell>
						<Cell>{addCommodityUnits(item.commodity)}</Cell>
						<Cell>${item.price}</Cell>
					</Row>
				{/each}
			</Body>
		</DataTable>
		{#if guides.length === 0}
			<P style="text-align: center;">Sin Resultados</P>
		{/if}
	</Card>
</section>

<SeparatorNotLine style="margin-bottom: 50px;" />

<!-- Create Guide -->

<svelte:head>
	<title>Guías</title>
</svelte:head>

<style>
	section {
		width: 80%;
		max-width: 900px;
		margin: 40px auto;
	}

	form {
		& .box_inputs {
			display: flex;
			justify-content: space-between;
		}
	}
</style>
